import { Montserrat, Source_Code_Pro } from 'next/font/google';
import clsx from 'clsx';
import type { Metadata } from 'next';
import './globals.css';

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
    display: 'swap',
});

const sourceCodePro = Source_Code_Pro({
    subsets: ['latin'],
    variable: '--font-source-code-pro',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={clsx(montserrat.variable, sourceCodePro.variable)}
        >
            <body>{children}</body>
        </html>
    );
}
